### ISSUE TITLE
Issue with Loading WhoisActive Results Due to Nested XML Nodes

### ISSUE THREAD

**Issue by Imran-imtiaz48** [amachanic/sp_whoisactive#119] opened 2024-06-28 19:55 UTC
I have a job that loads the WhoisActive results into a table every 30 seconds. However, I encounter an issue when the XML SQL_TEXT contains too many nested nodes, making it impossible to load the table. Is there a way to filter these records or another workaround? Loading this data into a table has been invaluable in helping us solve numerous issues.

**Comment by erikdarlingdata** [comment] 2024-06-28 20:19
This is a dupe of #111

**Closed by erikdarlingdata** 2024-06-28 20:19 UTC
