### ISSUE TITLE
request to add job_name and step_name in new columns

### ISSUE THREAD

**Issue by johnecono54** [amachanic/sp_whoisactive#86] opened 2022-05-27 20:25 UTC
would it be possible to have job_name & step_name in new columns instead of having it buried in the additional_info? Maybe with a new parameter? The program_name for SQLAgent jobs is pretty useless when trying to find what job is actually running, and it would be nice to have that broken out.

**Comment by erikdarlingdata** [comment] 2022-08-25 23:52
This is a duplicate of #66

**Closed by erikdarlingdata** 2022-08-25 23:52 UTC
