### ISSUE TITLE
An error occurred while executing batch. Error message is: Name cannot begin with the '>' character, hexadecimal value 0x3E. Line 126, position 22.

### ISSUE THREAD

**Issue by ghauan** [amachanic/sp_whoisactive#100] opened 2023-07-07 15:15 UTC
I get the above error if I am running `EXEC dbo.sp_WhoIsActive
        @get_transaction_info = 1,
        @get_outer_command = 1,
        @get_plans = 1,
        @get_task_info = 2,
        @get_additional_info = 1,
        @find_block_leaders = 1,
        @get_memory_info = 1`

while at the same time sp_blitzFirst is running. An example running in my environment: `exec sp_blitzfirst @expertmode=1,
@OutputDatabaseName = 'DBAtoolsHVI',
@OutputSchemaName = 'dbo',
@OutputTableName = 'BlitzFirst',
@OutputTableNameFileStats = 'BlitzFirst_FileStats',
@OutputTableNamePerfmonStats = 'BlitzFirst_PerfmonStats',
@OutputTableNameWaitStats = 'BlitzFirst_WaitStats',
@OutputTableNameBlitzCache = 'BlitzCache',
@OutputTableNameBlitzWho = 'BlitzWho'`

I have seen variations of the error message, I guess it has to do with where sp_blitzFirst is in its run. 
Another example: "An error occurred while executing batch. Error message is: Name cannot begin with the '=' character, hexadecimal value 0x3D. Line 1549, position 31."

I am running the latest version (12.0) of sp_whoisactive.

SErver: Microsoft SQL Server 2019 (RTM-CU20) (KB5024276) - 15.0.4312.2 (X64)   Apr  1 2023 12:10:46   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by erikdarlingdata** [comment] 2023-10-31 19:51
I think this is a duplicate of #99

**Closed by erikdarlingdata** 2023-10-31 19:51 UTC
